### ISSUE TITLE
BCR 四周年更新后如何安装证书？

### ISSUE THREAD

**Issue by libaibaba** [watermellye/Capture-pcr-API#1]
用的不同方法，今天更新后我的不行了，你的还可以吗

**Comment by chzhong** [comment]
国服更新后，由于安卓的安全机制问题，不能用作者的方法抓了（证书不被浏览器以外的程序信任）。
这里给出几个关键点，请自行研究：
1. 把模拟器的 Root 和系统盘可读写功能打开，重启模拟器。
2. 安卓版证书和之前一样在模拟器中用浏览器下载，然后到处到你电脑，用 `openssl x509 -subject_hash_old -in 安卓版证书.crt`  获取证书的 _subject_hash_。Windows 版的 [openssl 工具](https://slproweb.com/products/Win32OpenSSL.html) 自行下载。
3. 把证书重命名位 _subject_hash_.0
4. 安装 Root Explorer （RE文件管理器），把根目录mount为读写 r/w。
5. 用 RE 文件管理器把证书复制到  `/etc/security/cacerts/` 重启游戏即可。

参考 Mumu12 的方法，其他模拟器类似 https://mumu.163.com/help/20221018/35047_1047210.html

**Comment by watermellye** [comment]
很抱歉没有看到这条issue，但是这条回复我收到了邮箱提醒。

我昨天尝试抓包时也发现了此问题（网络错误1-2-0）。我并不从事这方面的工作，因此也不知道应该如何解决。

非常高兴有大佬不吝解答，我回头也试一下。

**Comment by watermellye** [comment]
详细操作

1. 把模拟器的 Root 和系统盘可读写功能打开，重启模拟器。
![20240424231555_rec_](https://github.com/watermellye/Capture-pcr-API/assets/22909197/501d6086-e76a-4241-9400-b8b707fb2bdb)
2. 导出证书
（图中演示步骤有些多余。`Download`文件夹也本身就在共享目录中。）
![20240424232509_rec_](https://github.com/watermellye/Capture-pcr-API/assets/22909197/6a8c493f-db5b-4509-bc8b-efcb963eea1a)
4. 下载安装openssl
（Light 版即可。安装时一路默认。）
https://slproweb.com/products/Win32OpenSSL.html
6. 获取证书的 subject_hash
`openssl x509 -subject_hash_old -in 刚导出的证书名.crt`
![20240424232932_rec_-convert](https://github.com/watermellye/Capture-pcr-API/assets/22909197/39a55d2b-6376-4345-a6cc-f8fd2d4d2544)
7. 重命名证书
把证书重命名为 <openssl console中显示的hash>.0
![20240424233327_rec_](https://github.com/watermellye/Capture-pcr-API/assets/22909197/16b2a16c-9dc0-4259-a0aa-a3f6c15d6f8d)
8. 下载 Root Explorer
（mumu 桌面上的“小工具”文件夹中自带一个RE。点击即可安装。）
（官方安装路径：https://rootexplorer.co/download/RootExplorer.apk）
![20240424233616_rec_-convert](https://github.com/watermellye/Capture-pcr-API/assets/22909197/90258dc1-08ac-4a65-a350-205cbd46e1a5)
9. 把根目录mount为读写 r/w
![20240424233809_rec_-convert](https://github.com/watermellye/Capture-pcr-API/assets/22909197/22f256d9-b65d-4d2e-9bd7-c25bdd67672e)
10. 把证书复制到 `/etc/security/cacerts/`
![20240424234128_rec_-convert](https://github.com/watermellye/Capture-pcr-API/assets/22909197/aa2c9be8-86ec-4e83-8ee3-0e0e5ddbb9b2)

然后就可以启动mitmdump，然后启动BCR抓包了
